import type { CSSProperties } from 'react';
import manifest from '../data/images.json';

type Entry = { base: string; width: number; height: number; widths: number[] } | { svg: true };
const images = manifest as Record<string, Entry>;

type Props = {
  src: string;
  alt: string;
  sizes?: string;
  className?: string;
  style?: CSSProperties;
  eager?: boolean;
};

/** Serves the WebP set generated by scripts/build-images.mjs, with srcset and intrinsic size. SVGs pass through. */
export const Img = ({ src, alt, sizes = '100vw', className, style, eager = false }: Props) => {
  const entry = images[src];
  const loading = eager ? 'eager' : 'lazy';
  if (!entry || 'svg' in entry) {
    return <img src={`/images/${src}`} alt={alt} className={className} style={style} loading={loading} decoding="async" />;
  }
  const { base, width, height, widths } = entry;
  const fallback = widths.includes(800) ? 800 : widths[widths.length - 1];
  return (
    <img
      src={`/images/${base}-${fallback}.webp`}
      srcSet={widths.map((w) => `/images/${base}-${w}.webp ${w}w`).join(', ')}
      sizes={sizes}
      width={width}
      height={height}
      alt={alt}
      className={className}
      style={style}
      loading={loading}
      decoding="async"
    />
  );
};
